services:
  - type: web
    name: docker-android
    env: docker
    plan: free
    region: oregon
    dockerfilePath: docker/emulator/Dockerfile
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
    envVars:
      - key: WEB_VNC
        value: "true"
